"""Generate Google Colab-compatible Jupyter notebooks from Manim animation code."""

import json
import re


def _make_markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def _make_code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "source": source.splitlines(keepends=True),
        "outputs": [],
        "execution_count": None,
    }


def _extract_scene_name(manim_code: str) -> str:
    """Extract the Scene class name from Manim code, defaulting to PaperAnimation."""
    match = re.search(r"class\s+(\w+)\s*\(\s*Scene\s*\)", manim_code)
    return match.group(1) if match else "PaperAnimation"


def generate_colab_notebook(
    manim_code: str,
    paper_title: str,
    paper_summary: str,
) -> dict:
    """Build a .ipynb dict that can be opened in Google Colab to run Manim animations."""

    scene_name = _extract_scene_name(manim_code)

    cells = [
        # --- Title & summary ---
        _make_markdown_cell(
            f"# {paper_title}\n\n{paper_summary}\n\n"
            "---\n"
            "*Notebook auto-generated by [visual-arxiv](https://github.com/visual-arxiv)*"
        ),
        # --- Setup ---
        _make_markdown_cell("## Setup\nInstall Manim and system dependencies for Colab."),
        _make_code_cell(
            "!pip install -q manim\n"
            "!apt-get install -qq -y libcairo2-dev libpango1.0-dev ffmpeg > /dev/null 2>&1"
        ),
        # --- Animation code ---
        _make_markdown_cell(
            "## Animation Code\n"
            "The Manim script below visualizes the core concepts of the paper."
        ),
        _make_code_cell(f"%%writefile animation.py\n{manim_code}"),
        # --- Render ---
        _make_markdown_cell("## Render the Animation"),
        _make_code_cell(f"!manim -ql animation.py {scene_name}"),
        # --- Display ---
        _make_markdown_cell("## Display the Result"),
        _make_code_cell(
            "import glob\n"
            "from IPython.display import Video\n\n"
            "videos = glob.glob('media/videos/animation/480p15/*.mp4')\n"
            "if videos:\n"
            "    display(Video(videos[0], embed=True))\n"
            "else:\n"
            "    print('No video found — check the render output above for errors.')"
        ),
    ]

    return {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {
                "provenance": [],
                "name": f"visual-arxiv: {paper_title}",
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3",
            },
            "language_info": {
                "name": "python",
            },
        },
        "cells": cells,
    }


def save_notebook(notebook: dict, path: str) -> None:
    """Write notebook dict to an .ipynb file."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
